### ISSUE TITLE
How to load raw audio file

### ISSUE THREAD

**Issue by cryax** [harritaylor/torch-vggish#2]
Can you provide an example of how to load a raw audio file and using vggish as feature extractor in pytorch?

**Comment by harritaylor** [comment]
Sure thing. I'll get a notebook written this week detailing it. It is however a drop-in replacement for vggish as provided by tensorflow, so if you use the preprocessing code provided at https://github.com/tensorflow/models/tree/master/research/audioset, it should work just the same in the meantime.

**Comment by harritaylor** [comment]
Hi @cryax, sorry about the delay - busy few weeks. Here's an example. Hope you find it useful.
https://github.com/harritaylor/torchvggish/blob/master/audio_embedding_example.ipynb
