### ISSUE TITLE
Missing activations.

### ISSUE THREAD

**Issue by keunhong** [harritaylor/torch-vggish#3]
I believe you're missing activations i.e. ReLU's for all of the layers.

**Comment by harritaylor** [comment]
Yep you’re right - I can’t believe I missed that! I haven’t needed to use the relu activations so I didn’t notice it. I’ll add it today.

Thanks,
Harri

Sent from mobile - usual limitations apply.

On 14 May 2019, at 10:02, Keunhong Park <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe you're missing activations i.e. ReLU's for all of the layers.

**Comment by harritaylor** [comment]
https://github.com/harritaylor/torch-vggish/commit/4d1f603fe94ed076879ca6e4379e0390bf5246e8 fixes this. Thanks for the heads up!

**Comment by keunhong** [comment]
Great! I want to note that in their Tensorflow code they also have a ReLU layer after the last FC layer (fc-2).

**Comment by harritaylor** [comment]
Ah! I missed that one too. I’m not familiar at all with tensorflow syntax. I’ll get that done tomorrow. Thanks again!

Thanks,
Harri

Sent from mobile - usual limitations apply.

On 14 May 2019, at 22:18, Keunhong Park <notifications@github.com<mailto:notifications@github.com>> wrote:


Great! I want to note that in their Tensorflow code they also have a ReLU layer after the last FC layer (fc-2).
