### ISSUE TITLE
questions about VGGISH_WEIGHTS 

### ISSUE THREAD

**Issue by cookingbear** [harritaylor/torch-vggish#7]
Thank you for your code and I wonder if your VGGISH_WEIGHTS from the path in the code is purely an adaption from google's checkpoint or your retrained result?

**Comment by harritaylor** [comment]
Hi, thanks for checking it out! 
Yes, I should clarify in the readme that this is a direct port - the embeddings that are created using torchvggish are identical to those created by the original vggish model.

I'm currently refactoring the code ready for a v1 release which should make things clearer & easier to use.
